version: '3.5'
services:
  php:
    image: arturgssjr/api-consulta-bigdata-kubernetes:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - APP_VERSION=${APP_VERSION}
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PRESTO_CONNECTION=${PRESTO_CONNECTION}
      - PRESTO_CATALOG=${PRESTO_CATALOG}
      - PRESTO_HOST=${PRESTO_HOST}
      - PRESTO_PORT=${PRESTO_PORT}
      - PRESTO_SCHEMA=${PRESTO_SCHEMA}
  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${DB_DATABASE}
  #     - MYSQL_USER=${DB_USERNAME}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - "3306:3306"
